unpackaged/objects/Error_Log__c.object
<CustomObject>
    <description>This object will store the error whenever the API call failed.</description>
    <fields>
        <fullName>Admin_Application_Id__c</fullName>
        <label>Admin Application Id</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Error_Message__c</fullName>
        <label>Error Message</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>IsResolved__c</fullName>
        <defaultValue>false</defaultValue>
        <label>IsResolved</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Json_Request_String__c</fullName>
        <label>Json Request String</label>
        <length>131072</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Object_Name__c</fullName>
        <label>Object Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Id__c</fullName>
        <label>Record Id</label>
        <length>30</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Record_Name__c</fullName>
        <label>Record Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Source_Class__c</fullName>
        <label>Source Class</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Stack_Trace__c</fullName>
        <label>Stack Trace</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Status_Code__c</fullName>
        <label>Status Code</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Status_Error__c</fullName>
        <label>Status Error</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>source_Method__c</fullName>
        <label>source Method</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Error Log</label>
    <nameField>
        <displayFormat>ERR-{0000}</displayFormat>
        <label>Error Log Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Error Logs</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

unpackaged/classes/ErrorLogClass.cls
/****************************************************************************************
* @Date         July 25th, 2018
* @Description  To insert the error on error object to track the error while sending data to the Admin
* @revision(s)
*
********************************************************************************************/
public class ErrorLogClass {
    
    /**********************************************************************
    * @Description Method to insert the error in the Error Log object
    * @param String, String, String, String, String, String, String, String
    * @return void
    ***********************************************************************/
    public static void LogError(String ErrorMessage, String StackTrace, String SourceClass, String SourceMethod, String ObjectName, String RecordName, String RecordId, string adminId, String JsonRequest, string statusError, integer statusCode ){
        try{
            Error_Log__c errorLog = new Error_Log__C();
            errorLog.Error_Message__c = ErrorMessage;
            errorLog.Stack_Trace__c = StackTrace;
            errorLog.Source_Class__c = SourceClass;
            errorLog.Source_Method__c = SourceMethod;
            errorLog.Object_Name__c = ObjectName;
            errorLog.Record_Name__c = RecordName;   
            errorLog.IsResolved__c = false;
            errorLog.Record_Id__c = RecordId;
            errorLog.Admin_Application_Id__c = adminId;
            errorLog.Status_Code__c = statusCode;
            errorLog.Status_Error__c = statusError;
            errorLog.Json_Request_String__c = String.isNotBlank(JsonRequest) && JsonRequest.length()<32768 ? JsonRequest : 'Please find the attachment for JSON';
            
            insert errorLog;
            
            if ( String.isNotBlank(JsonRequest) && JsonRequest.length() > 32768 ) {
                Attachment theAttachment = new Attachment();
                theAttachment.Body = Blob.valueOf(JsonRequest);
                theAttachment.Name = String.valueOf('JsonRequest.txt');
                theAttachment.ParentId = errorLog.Id; 
                insert theAttachment;
            }
        }
        catch(exception e){
            system.debug(LoggingLevel.ERROR, 'LogError method failed'+e.getMessage());
        }       
    }
}